/* Citadel client C ABI. Generated by cbindgen; do not edit by hand. */

#ifndef CITADEL_CLIENT_H
#define CITADEL_CLIENT_H

#pragma once

/* This header is generated from crates/citadel-client-ffi. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Stable ABI version. Bump on any breaking change to the C surface.
 */
#define CITADEL_FFI_ABI_VERSION 2

/**
 * Status codes returned by the C ABI. Stable, `#[repr(C)]`.
 */
typedef enum {
    /**
     * Operation succeeded (and, for poll, an envelope was written).
     */
    CITADEL_STATUS_OK = 0,
    /**
     * Non-fatal: nothing was available to poll right now; try again later.
     */
    CITADEL_STATUS_AGAIN = 1,
    /**
     * The connection is closed; no more envelopes will arrive.
     */
    CITADEL_STATUS_DISCONNECTED = 2,
    /**
     * A pointer was null or an argument was invalid.
     */
    CITADEL_STATUS_INVALID_ARGUMENT = 3,
    /**
     * Connecting or handshaking failed.
     */
    CITADEL_STATUS_CONNECT = 4,
    /**
     * Sending failed.
     */
    CITADEL_STATUS_SEND = 5,
    /**
     * Receiving/decoding failed.
     */
    CITADEL_STATUS_RECEIVE = 6,
    /**
     * An unexpected internal error (including a caught panic).
     */
    CITADEL_STATUS_INTERNAL = 7,
} CitadelStatus;

/**
 * Realtime auth outcome status returned by [`citadel_client_authenticate`].
 *
 * Values mirror the wire-level `AUTH_STATUS_*` constants exactly so engine
 * bindings can compare them with their generated/declaration-checked protocol
 * constants.
 */
typedef enum {
    /**
     * The token validated and `user_buf` contains the resolved user id.
     */
    CITADEL_AUTH_STATUS_AUTHENTICATED = 0,
    /**
     * The connection was admitted as an anonymous guest.
     */
    CITADEL_AUTH_STATUS_GUEST = 1,
    /**
     * The server refused the handshake; `out_reason` contains an `AUTH_REASON_*`.
     */
    CITADEL_AUTH_STATUS_REJECTED = 2,
} CitadelAuthStatus;

/**
 * The opaque client handle exposed to C as `CitadelClient *`.
 */
typedef struct CitadelClient CitadelClient;

/**
 * Opaque decoded DeltaBunch. Bytes are read with
 * [`citadel_rep_decoded_field_bytes`].
 */
typedef struct CitadelRepDecoded CitadelRepDecoded;

/**
 * Opaque DeltaBunch encoder handle exposed to C as `CitadelRepEncoder *`.
 */
typedef struct CitadelRepEncoder CitadelRepEncoder;

/**
 * Opaque shared transform runtime handle exposed as `CitadelTransformView *`.
 */
typedef struct CitadelTransformView CitadelTransformView;

/**
 * One replicated field's identity tuple, matching
 * `citadel_wire::schema::LayoutField` (the `schema_hash` preimage). `#[repr(C)]`.
 */
typedef struct {
    /**
     * Stable handle = index in the ordered table.
     */
    uint16_t field_id;
    /**
     * Field type discriminant.
     */
    uint16_t type_tag;
    /**
     * Codec id used to (de)serialize the field.
     */
    uint16_t codec_id;
    /**
     * Replication condition discriminant.
     */
    uint8_t cond;
    /**
     * Field authority discriminant.
     */
    uint8_t authority;
    /**
     * Codec-defined fixed-width bounds shape (folds the field's stable key).
     */
    uint64_t bounds_shape;
} CitadelSchemaField;

/**
 * A C-friendly schema entry for the scalar NetworkPeer codecs exposed by this
 * ABI. `kind`: 0=bool, 1=int range, 2=scalar, 3=bytes.
 */
typedef struct {
    uint8_t kind;
    int64_t int_min;
    int64_t int_max;
    float scalar_min;
    float scalar_max;
    uint32_t values_per_unit;
    uint32_t max_len;
} CitadelRepCodec;

/**
 * One decoded scalar value. `kind` uses the same tags as [`CitadelRepCodec`].
 */
typedef struct {
    uint16_t field_id;
    uint8_t kind;
    bool bool_value;
    int64_t int_value;
    float scalar_value;
    uintptr_t bytes_len;
} CitadelRepFieldValue;

/**
 * A transform returned by the shared runtime, in Citadel world units (cm).
 */
typedef struct {
    /**
     * Position `[x, y, z]`.
     */
    float position[3];
    /**
     * Quaternion `[x, y, z, w]`.
     */
    float rotation[4];
    /**
     * Linear velocity `[x, y, z]`.
     */
    float velocity[3];
} CitadelTransformState;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return the ABI version this library was built with.
 */
uint32_t citadel_client_abi_version(void);

/**
 * Connect to a Citadel QUIC endpoint.
 *
 * `addr` and `server_name` are NUL-terminated C strings. `insecure` selects dev
 * TLS that does not verify the server certificate (for the dev self-signed
 * cert). On success, writes a heap-allocated handle to `*out_handle`; the
 * caller owns it and must call [`citadel_client_free`].
 *
 * # Safety
 * `addr` and `server_name` must be valid NUL-terminated C strings.
 * `out_handle` must be a valid, writable `*mut *mut CitadelClient`.
 */
CitadelStatus citadel_client_connect_quic(const char *addr,
                                          const char *server_name,
                                          bool insecure,
                                          CitadelClient **out_handle);

/**
 * Connect to a Citadel WebSocket endpoint (e.g. `ws://127.0.0.1:7352/`).
 *
 * # Safety
 * `url` must be a valid NUL-terminated C string. `out_handle` must be a valid,
 * writable `*mut *mut CitadelClient`.
 */
CitadelStatus citadel_client_connect_websocket(const char *url, CitadelClient **out_handle);

/**
 * Send an envelope. `reliable` chooses a reliable stream vs an unreliable
 * datagram on QUIC; WebSocket is always reliable. The `data`/`len` bytes are
 * copied; the caller keeps ownership of its buffer.
 *
 * # Safety
 * `handle` must be a valid pointer returned by a `connect` function and not yet
 * freed. `data` must point to at least `len` readable bytes (or be null iff
 * `len == 0`).
 */
CitadelStatus citadel_client_send(CitadelClient *handle,
                                  uint16_t kind,
                                  const uint8_t *data,
                                  uintptr_t len,
                                  bool reliable);

/**
 * Perform the realtime auth handshake as the next frame on a freshly connected
 * transport.
 *
 * `token`/`len` is copied into a `KIND_AUTH` body; pass null + 0 for an explicit
 * guest session. On [`CitadelStatus::Ok`], `*out_status` is set to the resolved
 * auth status. For authenticated sessions, the user id is copied into
 * `user_buf` as a NUL-terminated UTF-8 string when `user_cap > 0`; `*out_user_len`
 * receives the full user-id length even when truncated. For rejected sessions,
 * `*out_reason` receives the coarse `AUTH_REASON_*` class.
 *
 * # Safety
 * `handle` must be a valid pointer returned by a `connect` function and not yet
 * freed. `token` must point to at least `len` readable bytes (or be null iff
 * `len == 0`). `out_status`, `out_user_len`, and `out_reason` must be writable.
 * `user_buf` must point to at least `user_cap` writable bytes (or be null iff
 * `user_cap == 0`).
 */
CitadelStatus citadel_client_authenticate(CitadelClient *handle,
                                          const uint8_t *token,
                                          uintptr_t len,
                                          CitadelAuthStatus *out_status,
                                          char *user_buf,
                                          uintptr_t user_cap,
                                          uintptr_t *out_user_len,
                                          uint8_t *out_reason);

/**
 * Poll for the next inbound envelope (non-blocking).
 *
 * On [`CitadelStatus::Ok`], writes the envelope kind to `*out_kind`, copies the
 * payload into the caller's `buf` (capacity `cap`), writes the payload length to
 * `*out_len`, and sets `*out_truncated` to true if the payload did not fit
 * (in which case only `cap` bytes were written). Returns [`CitadelStatus::Again`]
 * if nothing is ready, or [`CitadelStatus::Disconnected`] if the connection
 * closed and the queue is drained.
 *
 * # Safety
 * `handle` must be a live handle. `out_kind`, `out_len`, and `out_truncated`
 * must be valid writable pointers. `buf` must point to at least `cap` writable
 * bytes (or be null iff `cap == 0`).
 */
CitadelStatus citadel_client_poll(CitadelClient *handle,
                                  uint16_t *out_kind,
                                  uint8_t *buf,
                                  uintptr_t cap,
                                  uintptr_t *out_len,
                                  bool *out_truncated);

/**
 * Copy the last error message for `handle` into `buf` as a NUL-terminated
 * string (truncated to `cap`). Returns the number of bytes written including
 * the NUL, or 0 on invalid arguments.
 *
 * # Safety
 * `handle` must be a live handle. `buf` must point to at least `cap` writable
 * bytes (or be null iff `cap == 0`).
 */
uintptr_t citadel_client_last_error(CitadelClient *handle, char *buf, uintptr_t cap);

/**
 * Free a client handle. After this call the pointer is invalid and must not be
 * used again. Passing null is a no-op.
 *
 * # Safety
 * `handle` must be a pointer returned by a `connect` function that has not
 * already been freed, or null.
 */
void citadel_client_free(CitadelClient *handle);

/**
 * Quantize a scalar to its integer code using the bounded fixed-point codec.
 *
 * Writes the code to `*out_code`. Returns [`CitadelStatus::InvalidArgument`]
 * for a null out-pointer, an invalid spec (`max <= min`, `values_per_unit == 0`,
 * non-finite bound), or a `NaN` value (`±Inf` saturate to the bounds).
 *
 * # Safety
 * `out_code` must be a valid, writable `*mut u64`.
 */
CitadelStatus citadel_quantize_scalar(float min,
                                      float max,
                                      uint32_t values_per_unit,
                                      float value,
                                      uint64_t *out_code);

/**
 * Dequantize a scalar code back to its value using the bounded fixed-point
 * codec. Writes the value to `*out_value`. Returns
 * [`CitadelStatus::InvalidArgument`] for a null out-pointer, an invalid spec,
 * or a code outside the codec's valid range (a malformed frame).
 *
 * # Safety
 * `out_value` must be a valid, writable `*mut f32`.
 */
CitadelStatus citadel_dequantize_scalar(float min,
                                        float max,
                                        uint32_t values_per_unit,
                                        uint64_t code,
                                        float *out_value);

/**
 * Encode a quaternion `(x, y, z, w)` to its smallest-three code representation.
 *
 * `quat` points to 4 floats `[x, y, z, w]`. `bits_per_component` is `9`, `10`,
 * or `15`. Writes the 2-bit dropped index to `*out_index` and the three kept
 * component codes to `out_codes[0..3]`. Degenerate inputs (`NaN`/zero-norm)
 * encode as identity. Returns [`CitadelStatus::InvalidArgument`] on a null
 * pointer or unsupported `bits_per_component`.
 *
 * # Safety
 * `quat` must point to 4 readable floats; `out_index` to a writable `u8`;
 * `out_codes` to 3 writable `u64`.
 */
CitadelStatus citadel_quat_encode_components(const float *quat,
                                             uint32_t bits_per_component,
                                             uint8_t *out_index,
                                             uint64_t *out_codes);

/**
 * Decode a smallest-three quaternion from its code representation into
 * `out_quat[0..4]` = `[x, y, z, w]`. `index` is masked to `0..=3` and codes to
 * the mode width, so no input panics or produces `NaN`. Returns
 * [`CitadelStatus::InvalidArgument`] on a null pointer or unsupported
 * `bits_per_component`.
 *
 * # Safety
 * `codes` must point to 3 readable `u64`; `out_quat` to 4 writable floats.
 */
CitadelStatus citadel_quat_decode_components(uint8_t index,
                                             const uint64_t *codes,
                                             uint32_t bits_per_component,
                                             float *out_quat);

/**
 * Compute the wide canonical 128-bit schema hash for an ordered field layout,
 * writing the digest to `out_hash[0..16]`. Returns [`CitadelStatus::InvalidArgument`]
 * for a null pointer, or if the fields are not strictly ascending by `field_id`
 * (the canonical-ordering requirement) or exceed the count slot.
 *
 * # Safety
 * `fields` must point to `count` readable [`CitadelSchemaField`]; `out_hash`
 * must point to at least 16 writable bytes (or `fields` may be null iff
 * `count == 0`).
 */
CitadelStatus citadel_schema_hash(uint32_t layout_version,
                                  const CitadelSchemaField *fields,
                                  uintptr_t count,
                                  uint8_t *out_hash);

/**
 * Decode one authoritative DeltaBunch with the caller's ordered field codecs.
 * `schema_hash` is the canonical 16-byte identity for this ordered field table.
 *
 * # Safety
 * `body`, `schema_hash`, and `codecs` must point to their declared readable
 * ranges (or be null only for a zero length); `out_decoded` must be writable.
 */
CitadelStatus citadel_rep_decode(const uint8_t *body,
                                 uintptr_t body_len,
                                 const uint8_t *schema_hash,
                                 uint32_t layout_version,
                                 const CitadelRepCodec *codecs,
                                 uintptr_t codec_count,
                                 CitadelRepDecoded **out_decoded);

/**
 * # Safety
 * `decoded` must be a live decoded handle and every output pointer writable.
 */
CitadelStatus citadel_rep_decoded_header(const CitadelRepDecoded *decoded,
                                         uint32_t *out_object_id,
                                         bool *out_is_full,
                                         uint64_t *out_result_id,
                                         uint64_t *out_base_id);

/**
 * # Safety
 * `decoded` must be a live decoded handle or null.
 */
uintptr_t citadel_rep_decoded_field_count(const CitadelRepDecoded *decoded);

/**
 * # Safety
 * `decoded` must be live and `out` writable.
 */
CitadelStatus citadel_rep_decoded_field_at(const CitadelRepDecoded *decoded,
                                           uintptr_t index,
                                           CitadelRepFieldValue *out);

/**
 * # Safety
 * `decoded` must be live; `buf` and `out_len` must cover their declared ranges.
 */
CitadelStatus citadel_rep_decoded_field_bytes(const CitadelRepDecoded *decoded,
                                              uintptr_t index,
                                              uint8_t *buf,
                                              uintptr_t cap,
                                              uintptr_t *out_len);

/**
 * # Safety
 * `decoded` must be null or an unfreed handle returned by `citadel_rep_decode`.
 */
void citadel_rep_decoded_free(CitadelRepDecoded *decoded);

/**
 * Create a DeltaBunch encoder. `is_full` selects a full snapshot (`base_id`
 * ignored, must set the schema via [`citadel_rep_encoder_set_schema`]);
 * otherwise `base_id` must be the nonzero base token. `result_id` must be
 * nonzero. `num_fields` is the class's field count (the changed_mask width).
 * Returns null on invalid arguments (zero `result_id`, or non-full with zero
 * `base_id`).
 */
CitadelRepEncoder *citadel_rep_encoder_new(uint32_t object_id,
                                           bool is_full,
                                           uint64_t result_id,
                                           uint64_t base_id,
                                           uintptr_t num_fields);

/**
 * Set the full-snapshot schema identity (the `hash` from [`citadel_schema_hash`]
 * and its `layout_version`). Required before finishing an `is_full` bunch.
 *
 * # Safety
 * `enc` must be a live encoder; `hash` must point to 16 readable bytes.
 */
CitadelStatus citadel_rep_encoder_set_schema(CitadelRepEncoder *enc,
                                             const uint8_t *hash,
                                             uint32_t layout_version);

/**
 * Add a boolean field to the bunch.
 *
 * # Safety
 * `enc` must be a live encoder handle.
 */
CitadelStatus citadel_rep_encoder_add_bool(CitadelRepEncoder *enc, uint16_t field_id, bool value);

/**
 * Add a bounded integer field (encoded in `ceil_log2(max-min+1)` bits).
 *
 * # Safety
 * `enc` must be a live encoder handle.
 */
CitadelStatus citadel_rep_encoder_add_int(CitadelRepEncoder *enc,
                                          uint16_t field_id,
                                          int64_t min,
                                          int64_t max,
                                          int64_t value);

/**
 * Add a bounded fixed-point scalar field.
 *
 * # Safety
 * `enc` must be a live encoder handle.
 */
CitadelStatus citadel_rep_encoder_add_scalar(CitadelRepEncoder *enc,
                                             uint16_t field_id,
                                             float min,
                                             float max,
                                             uint32_t values_per_unit,
                                             float value);

/**
 * Add a length-delimited byte field (capped at `max_len`).
 *
 * # Safety
 * `enc` must be a live encoder handle; `data` must point to `len` readable bytes
 * (or be null iff `len == 0`).
 */
CitadelStatus citadel_rep_encoder_add_bytes(CitadelRepEncoder *enc,
                                            uint16_t field_id,
                                            uint32_t max_len,
                                            const uint8_t *data,
                                            uintptr_t len);

/**
 * Finish the bunch, encoding it into the caller's `buf` (capacity `cap`). Writes
 * the encoded length to `*out_len` and sets `*out_truncated` if it did not fit.
 * The encoder is NOT freed; call [`citadel_rep_encoder_free`] after. Returns
 * [`CitadelStatus::InvalidArgument`] if a prior `add_*`/`set_schema` failed or an
 * argument was invalid; [`CitadelStatus::Internal`] if encoding itself failed.
 *
 * # Safety
 * `enc` must be a live encoder handle. `out_len`/`out_truncated` must be writable;
 * `buf` must point to at least `cap` writable bytes (or be null iff `cap == 0`).
 */
CitadelStatus citadel_rep_encoder_finish(CitadelRepEncoder *enc,
                                         uint8_t *buf,
                                         uintptr_t cap,
                                         uintptr_t *out_len,
                                         bool *out_truncated);

/**
 * Free a DeltaBunch encoder. Passing null is a no-op.
 *
 * # Safety
 * `enc` must be a handle from [`citadel_rep_encoder_new`] not already freed, or
 * null.
 */
void citadel_rep_encoder_free(CitadelRepEncoder *enc);

/**
 * Build a transform runtime from the reliable `KIND_TSYNC_HELLO` body.
 *
 * # Safety
 * `hello_body` must reference `hello_len` readable bytes (or be null only when
 * `hello_len == 0`), and `out_view` must be a writable pointer.
 */
CitadelStatus citadel_transform_view_new(const uint8_t *hello_body,
                                         uintptr_t hello_len,
                                         CitadelTransformView **out_view);

/**
 * Decode and apply one `KIND_TSYNC_SNAPSHOT` body. `out_applied` reports false
 * for malformed, stale, or missing-base snapshots; those are normal datagram
 * conditions, not transport errors.
 *
 * # Safety
 * `view` must be live, `body` must reference `body_len` readable bytes (or be
 * null when zero), and `out_applied` must be writable.
 */
CitadelStatus citadel_transform_view_apply_datagram(CitadelTransformView *view,
                                                    const uint8_t *body,
                                                    uintptr_t body_len,
                                                    bool *out_applied);

/**
 * Return the runtime's current adaptive-buffer sample for an object.
 *
 * # Safety
 * `view` must be live and `out_state`/`out_found` must be writable.
 */
CitadelStatus citadel_transform_view_sample_now(CitadelTransformView *view,
                                                uint32_t object_id,
                                                CitadelTransformState *out_state,
                                                bool *out_found);

/**
 * Return an owned object's present authoritative state and highest contiguous
 * input acknowledgement, the required reconciliation target.
 *
 * # Safety
 * `view` must be live and all output pointers must be writable.
 */
CitadelStatus citadel_transform_view_authoritative_state(CitadelTransformView *view,
                                                         uint32_t object_id,
                                                         CitadelTransformState *out_state,
                                                         uint32_t *out_input_seq,
                                                         bool *out_found);

/**
 * Encode the snapshot acknowledgement into `out_ack[0..8]`.
 *
 * # Safety
 * `view` must be live and `out_ack` must reference at least eight writable bytes.
 */
CitadelStatus citadel_transform_view_ack(CitadelTransformView *view, uint8_t *out_ack);

/**
 * Encode one sequenced owner-input frame as `KIND_TSYNC_INPUT`'s body. Engine
 * components retain and resend recent frames as their own bounded redundancy
 * ring; this function keeps the wire layout itself in Rust.
 *
 * # Safety
 * `out`, `out_len`, and `out_truncated` must be writable. `out` may be null
 * only when `cap == 0`.
 */
CitadelStatus citadel_transform_encode_input(uint32_t input_seq,
                                             uint32_t sim_tick,
                                             float dt,
                                             uint32_t object_id,
                                             uint32_t ownership_epoch,
                                             float velocity_x,
                                             float velocity_y,
                                             float velocity_z,
                                             uint8_t *out,
                                             uintptr_t cap,
                                             uintptr_t *out_len,
                                             bool *out_truncated);

/**
 * Free a transform runtime handle. Passing null is a no-op.
 *
 * # Safety
 * `view` must be a live handle returned by citadel_transform_view_new or null.
 */
void citadel_transform_view_free(CitadelTransformView *view);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CITADEL_CLIENT_H */
